title: "PhuBlog"
description: "A personal tech blog powered by GitHub Pages & Jekyll with advanced features."
baseurl: ""  # for GitHub Pages, keep empty
url: "https://phuchungbhutia.github.io"
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
