name: Generate blogs.json and commit

on:
  push:
    branches:
      - main
    paths:
      - 'blogs/**'
      - 'scripts/**'
      - 'package.json'
  workflow_dispatch:

jobs:
  generate-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Generate blogs.json
        run: node scripts/generate-blogs-json.js

      - name: Check for changes
        run: |
          git status
          git diff

      - name: Commit & Push blogs.json if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add blogs.json
          if ! git diff --cached --quiet; then
            git commit -m "Update blogs.json [skip ci]"
            git push
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
