name: Generate Blogs JSON

on:
  push:
    paths:
      - 'blogs/**.md'
      - 'scripts/generate-blogs-json.js'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Generate blogs.json
        run: node scripts/generate-blogs-json.js

      - name: Commit changes
        run: |
          git config --global user.name 'phubot'
          git config --global user.email 'phubot@example.com'
          git add blogs.json
          git commit -m '🤖 Auto-update blogs.json' || echo "No changes to commit"
          git push
