name: Generate blogs.json and commit

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Generate blogs.json
        run: node scripts/generate-blogs-json.js

      - name: Show git status after generation
        run: |
          git status
          git diff

      - name: Commit and push blogs.json
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add blogs.json
          git diff --cached --quiet || git commit -m "Auto-update blogs.json"
          git push
        env:
          # Needed if your repo is private or requires auth. For public repos, this might be unnecessary.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
